##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
  # Plugin configuration
  [plugins.inputs]
  SEATABLE_TABLE_NAME = "Table1,Table2"
  DATA_FOLDER = "assets/data"

[build]
# Dummy build command
command = "echo onBuild"

[build.environment]
NODE_VERSION = "14.14.0"
